import React, { useState } from "react";
import { useApp } from "@/contexts/AppContext";
import Navbar from "@/components/layout/Navbar";
import TeacherSidebar from "@/components/layout/TeacherSidebar";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { audioSynth } from "@/services/audioSynth";
import confetti from "canvas-confetti";
import {
  Sparkles,
  CheckCircle2,
} from "@/components/ui/icons";

export default function QuizStudioPage() {
  const { documents, classrooms, createTask } = useApp();

  const [selectedClassId, setSelectedClassId] = useState<string>("cls_bio_10a");
  const [selectedDocId, setSelectedDocId] = useState<string>("doc_bio_01");
  const [targetTopic, setTargetTopic] = useState("Enzim & Organ Pencernaan Kimiawi");
  const [isGenerating, setIsGenerating] = useState(false);

  // Draft state generated by RAG AI
  const [draftQuestions, setDraftQuestions] = useState<any[]>([
    {
      id: "draft_1",
      questionText:
        "Berdasarkan Modul BAB 3, pada kondisi pH berapakah enzim pepsin di dalam ventrikulus (lambung) bekerja secara optimal?",
      options: ["pH 1.5 - 2.0 (Asam Kuat)", "pH 6.8 (Netral)", "pH 8.2 (Basa)", "pH 12.0 (Basa Kuat)"],
      correctIndex: 0,
      difficulty: "MEDIUM",
      sourceReference: "Modul Guru BAB 3 Halaman 48 (VEC-BIO-301)",
    },
    {
      id: "draft_2",
      questionText:
        "Bagian usus manakah yang memiliki vili dan mikrovili untuk menyerap glukosa dan asam amino langsung ke aliran darah?",
      options: ["Ileum (Usus Penyerapan)", "Duodenum (Usus 12 Jari)", "Esofagus", "Kolon Asenden"],
      correctIndex: 0,
      difficulty: "CHALLENGING",
      sourceReference: "Modul Guru BAB 3 Halaman 52 (VEC-BIO-301)",
    },
  ]);

  const [isPublished, setIsPublished] = useState(false);

  const handleGenerateAI = () => {
    setIsGenerating(true);
    audioSynth.playClickSound();

    setTimeout(() => {
      setIsGenerating(false);
      audioSynth.playSuccessSound();
      setDraftQuestions((prev) => [
        ...prev,
        {
          id: `draft_${Date.now()}`,
          questionText:
            "Enzim tripsinogen diubah menjadi tripsin aktif oleh senyawa aktivator bernama...",
          options: ["Enterokinase", "Pepsinogen", "HCl", "Saliva"],
          correctIndex: 0,
          difficulty: "MASTERY",
          sourceReference: "Modul Guru BAB 3 Halaman 55",
        },
      ]);
    }, 1500);
  };

  const handlePublishToClass = () => {
    audioSynth.playLevelUpSound();
    confetti({ particleCount: 80, spread: 60 });

    const selectedCls = classrooms.find((c) => c.id === selectedClassId);

    createTask({
      classroomId: selectedClassId,
      classroomName: selectedCls?.name || "Biologi 10-A",
      type: "quiz",
      title: `Kuis Adaptif: ${targetTopic}`,
      chapter: "BAB 3 - Sistem Pencernaan",
      sourceReference: "Modul Guru RAG VEC-BIO-301",
      difficultyLevel: "BASIC",
      isPublished: true,
      dueDate: "2026-08-30T23:59:00.000Z",
      contentJson: {
        overview: "Kuis yang dibuat melalui AI Quiz Studio dan disetujui guru pengajar.",
        questions: draftQuestions,
      },
    });

    setIsPublished(true);
  };

  return (
    <div className="min-h-screen bg-[#FBF9F4] text-[#1B1C19]">
      <Navbar />

      <div className="flex">
        <TeacherSidebar />

        <main className="flex-1 p-6 sm:p-10 max-w-6xl space-y-8">
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <Badge variant="mint" className="text-xs">
                  Teacher-in-the-Loop Studio
                </Badge>
                <Badge variant="lavender" className="text-xs">
                  RAG Grounding
                </Badge>
              </div>
              <h1 className="text-2xl sm:text-4xl font-bold text-[#010105]">
                AI-Assisted Task &amp; Quiz Generator Studio
              </h1>
              <p className="text-xs sm:text-sm text-[#5A5E70] font-medium mt-0.5">
                Susun draf soal adaptif berbasis dokumen modul guru. Guru memegang kendali penuh untuk mereview, mengedit, dan menyetujui sebelum publikasi.
              </p>
            </div>
          </div>

          {/* GENERATOR CONFIGURATION CARD */}
          <Card className="p-6 bg-white rounded-3xl border border-[rgba(28,30,38,0.06)] shadow-xs space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div>
                <label className="block text-xs font-bold text-[#010105] mb-1">Target Kelas</label>
                <select
                  value={selectedClassId}
                  onChange={(e) => setSelectedClassId(e.target.value)}
                  className="w-full p-2.5 rounded-2xl border border-[rgba(28,30,38,0.1)] text-xs font-bold text-[#010105] bg-[#FBF9F4] focus:outline-none"
                >
                  {classrooms.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-[#010105] mb-1">Modul Sumber RAG</label>
                <select
                  value={selectedDocId}
                  onChange={(e) => setSelectedDocId(e.target.value)}
                  className="w-full p-2.5 rounded-2xl border border-[rgba(28,30,38,0.1)] text-xs font-bold text-[#010105] bg-[#FBF9F4] focus:outline-none"
                >
                  {documents.map((d) => (
                    <option key={d.id} value={d.id}>
                      {d.title}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-[#010105] mb-1">Topik Spesifik</label>
                <Input
                  value={targetTopic}
                  onChange={(e) => setTargetTopic(e.target.value)}
                  className="text-xs"
                />
              </div>
            </div>

            <div className="flex justify-between items-center pt-2 border-t border-[rgba(28,30,38,0.06)]">
              <span className="text-xs text-[#5A5E70] font-medium">
                Prompt akan dicocokkan dengan similarity score embedding ChromaDB.
              </span>
              <Button
                onClick={handleGenerateAI}
                disabled={isGenerating}
                variant="primary"
                size="sm"
                className="font-bold text-xs"
              >
                <Sparkles className="w-4 h-4 mr-1.5" />
                {isGenerating ? "Menghasilkan Draf Soal..." : "Generate Draf Soal via AI RAG"}
              </Button>
            </div>
          </Card>

          {/* DRAFT QUESTIONS REVIEW & APPROVAL LIST */}
          <section className="space-y-4">
            <div className="flex justify-between items-center">
              <h2 className="text-lg font-bold text-[#010105]">
                Draf Soal Kuis ({draftQuestions.length} Soal Ter-grounding)
              </h2>
              <Badge variant="butter" className="text-xs">
                Perlu Persetujuan Guru
              </Badge>
            </div>

            <div className="space-y-4">
              {draftQuestions.map((q, qIdx) => (
                <Card key={q.id || qIdx} className="p-6 bg-white rounded-3xl border border-[rgba(28,30,38,0.06)] shadow-xs space-y-3">
                  <div className="flex justify-between items-start">
                    <div className="flex items-center gap-2">
                      <span className="w-6 h-6 rounded-full bg-[#1C1E26] text-white flex items-center justify-center text-xs font-bold">
                        {qIdx + 1}
                      </span>
                      <Badge variant="lavender" className="text-[10px]">
                        Level {q.difficulty}
                      </Badge>
                    </div>
                    <span className="text-[10px] font-mono text-[#9195A8]">
                      {q.sourceReference}
                    </span>
                  </div>

                  <p className="text-sm font-bold text-[#010105]">{q.questionText}</p>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
                    {q.options.map((opt: string, optIdx: number) => (
                      <div
                        key={optIdx}
                        className={`p-3 rounded-2xl text-xs font-medium border ${
                          optIdx === q.correctIndex
                            ? "bg-[#D1EBE1] border-[#1D5E4D] text-[#1D5E4D] font-bold"
                            : "bg-[#FBF9F4] border-[rgba(28,30,38,0.06)] text-[#5A5E70]"
                        }`}
                      >
                        <span className="font-bold mr-1.5">{String.fromCharCode(65 + optIdx)}.</span>
                        {opt}
                      </div>
                    ))}
                  </div>
                </Card>
              ))}
            </div>

            {/* Bottom Actions */}
            <div className="pt-4 flex flex-col sm:flex-row items-center justify-between gap-4">
              {isPublished ? (
                <div className="flex items-center gap-2 text-xs font-bold text-[#1D5E4D]">
                  <CheckCircle2 className="w-4 h-4" /> Kuis berhasil disetujui &amp; diterbitkan ke portal siswa!
                </div>
              ) : (
                <span className="text-xs text-[#5A5E70] font-medium">
                  Pastikan seluruh soal telah ditelaah sesuai kurikulum sebelum diterbitkan.
                </span>
              )}

              <Button
                onClick={handlePublishToClass}
                disabled={draftQuestions.length === 0}
                variant="primary"
                size="lg"
                className="font-bold shadow-md w-full sm:w-auto"
              >
                <CheckCircle2 className="w-4 h-4 mr-1.5" />
                Setujui &amp; Terbitkan Kuis ke Portal Siswa
              </Button>
            </div>
          </section>
        </main>
      </div>
    </div>
  );
}
