import React, { useState } from "react";
import { useApp } from "@/contexts/AppContext";
import Navbar from "@/components/layout/Navbar";
import TeacherSidebar from "@/components/layout/TeacherSidebar";
import { Input } from "@/components/ui/input";
import { audioSynth } from "@/services/audioSynth";
import confetti from "canvas-confetti";
import {
  Sparkles,
  CheckCircle2,
  Database,
  ArrowRight,
  School,
  FileText,
} from "@/components/ui/icons";

export default function QuizStudioPage() {
  const { documents, classrooms, createTask } = useApp();

  const [selectedClassId, setSelectedClassId] = useState<string>("cls_bio_10a");
  const [selectedDocId, setSelectedDocId] = useState<string>("doc_bio_01");
  const [targetTopic, setTargetTopic] = useState("Enzim & Organ Pencernaan Kimiawi");
  const [isGenerating, setIsGenerating] = useState(false);

  // Draft state generated by RAG AI
  const [draftQuestions, setDraftQuestions] = useState<any[]>([
    {
      id: "draft_1",
      questionText:
        "Berdasarkan Modul BAB 3, pada kondisi pH berapakah enzim pepsin di dalam ventrikulus (lambung) bekerja secara optimal?",
      options: ["pH 1.5 - 2.0 (Asam Kuat)", "pH 6.8 (Netral)", "pH 8.2 (Basa)", "pH 12.0 (Basa Kuat)"],
      correctIndex: 0,
      difficulty: "MEDIUM",
      sourceReference: "Modul Guru BAB 3 Halaman 48 (VEC-BIO-301)",
    },
    {
      id: "draft_2",
      questionText:
        "Bagian usus manakah yang memiliki vili dan mikrovili untuk menyerap glukosa dan asam amino langsung ke aliran darah?",
      options: ["Ileum (Usus Penyerapan)", "Duodenum (Usus 12 Jari)", "Esofagus", "Kolon Asenden"],
      correctIndex: 0,
      difficulty: "CHALLENGING",
      sourceReference: "Modul Guru BAB 3 Halaman 52 (VEC-BIO-301)",
    },
  ]);

  const [isPublished, setIsPublished] = useState(false);

  const handleGenerateAI = () => {
    setIsGenerating(true);
    audioSynth.playClickSound();

    setTimeout(() => {
      setIsGenerating(false);
      audioSynth.playSuccessSound();
      setDraftQuestions((prev) => [
        ...prev,
        {
          id: `draft_${Date.now()}`,
          questionText:
            "Enzim tripsinogen diubah menjadi tripsin aktif oleh senyawa aktivator bernama...",
          options: ["Enterokinase", "Pepsinogen", "HCl", "Saliva"],
          correctIndex: 0,
          difficulty: "MASTERY",
          sourceReference: "Modul Guru BAB 3 Halaman 55",
        },
      ]);
    }, 1500);
  };

  const handlePublishToClass = () => {
    audioSynth.playLevelUpSound();
    confetti({ particleCount: 80, spread: 60 });

    const selectedCls = classrooms.find((c) => c.id === selectedClassId);

    createTask({
      classroomId: selectedClassId,
      classroomName: selectedCls?.name || "Biologi 10-A",
      type: "quiz",
      title: `Kuis Adaptif: ${targetTopic}`,
      chapter: "BAB 3 - Sistem Pencernaan",
      sourceReference: "Modul Guru RAG VEC-BIO-301",
      difficultyLevel: "BASIC",
      isPublished: true,
      dueDate: "2026-08-30T23:59:00.000Z",
      contentJson: {
        overview: "Kuis yang dibuat melalui AI Quiz Studio dan disetujui guru pengajar.",
        questions: draftQuestions,
      },
    });

    setIsPublished(true);
  };

  return (
    <div className="min-h-screen bg-[#F8F9FD] text-[#1C1E26] flex flex-col">
      <Navbar />

      <div className="flex flex-1 min-h-[calc(100vh-4rem)]">
        {/* Responsive Desktop Sidebar */}
        <TeacherSidebar />

        {/* Main Content Area */}
        <main className="flex-1 min-w-0 p-4 sm:p-6 lg:p-8 max-w-7xl overflow-x-hidden space-y-6 sm:space-y-8">
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-1.5">
                <span className="clay-pill clay-mint px-3 py-0.5 text-xs font-extrabold text-[#1D5E4D]">
                  Teacher-in-the-Loop Studio
                </span>
                <span className="clay-pill clay-lavender px-3 py-0.5 text-xs font-bold text-[#4B3B7A]">
                  RAG Grounding Verified
                </span>
              </div>
              <h1 className="text-2xl sm:text-3xl font-black text-[#010105] tracking-tight">
                AI-Assisted Task &amp; Quiz Generator Studio
              </h1>
              <p className="text-xs sm:text-sm text-[#5A5E70] font-medium mt-1">
                Susun draf soal adaptif berbasis dokumen modul guru. Guru memegang kendali penuh untuk mereview, mengedit, dan menyetujui sebelum publikasi.
              </p>
            </div>
          </div>

          {/* GENERATOR CONFIGURATION CARD */}
          <div className="clay-card clay-white p-6 space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div>
                <label className="block text-xs font-bold text-[#010105] mb-1">Target Kelas</label>
                <select
                  value={selectedClassId}
                  onChange={(e) => setSelectedClassId(e.target.value)}
                  className="w-full p-2.5 rounded-2xl border border-[rgba(28,30,38,0.1)] text-xs font-bold text-[#010105] bg-[#F8F9FD] focus:outline-none cursor-pointer"
                >
                  {classrooms.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-[#010105] mb-1">Modul Sumber RAG</label>
                <select
                  value={selectedDocId}
                  onChange={(e) => setSelectedDocId(e.target.value)}
                  className="w-full p-2.5 rounded-2xl border border-[rgba(28,30,38,0.1)] text-xs font-bold text-[#010105] bg-[#F8F9FD] focus:outline-none cursor-pointer"
                >
                  {documents.map((d) => (
                    <option key={d.id} value={d.id}>
                      {d.title}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-[#010105] mb-1">Topik Spesifik</label>
                <Input
                  value={targetTopic}
                  onChange={(e) => setTargetTopic(e.target.value)}
                  className="text-xs bg-[#F8F9FD] rounded-2xl"
                />
              </div>
            </div>

            <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-3 pt-3 border-t border-[rgba(28,30,38,0.06)]">
              <span className="text-xs text-[#5A5E70] font-medium">
                Prompt dicocokkan dengan kemiripan vektor ChromaDB dari modul guru.
              </span>
              <button
                onClick={handleGenerateAI}
                disabled={isGenerating}
                className="clay-btn clay-btn-dark px-4 py-2.5 text-xs font-black flex items-center gap-1.5 cursor-pointer self-start sm:self-auto"
              >
                <Sparkles className="w-4 h-4" />
                <span>{isGenerating ? "Menghasilkan Draf Soal..." : "Generate Draf Soal via AI RAG"}</span>
              </button>
            </div>
          </div>

          {/* DRAFT QUESTIONS REVIEW & APPROVAL LIST */}
          <section className="space-y-4">
            <div className="flex justify-between items-center">
              <div>
                <h2 className="text-lg font-black text-[#010105]">
                  Draf Soal Kuis ({draftQuestions.length} Soal Ter-grounding)
                </h2>
                <p className="text-xs text-[#5A5E70]">
                  Setiap butir soal memiliki sitasi halaman dari dokumen ajar asli.
                </p>
              </div>
              <span className="clay-pill clay-butter px-3 py-1 text-xs font-extrabold text-[#785308]">
                Perlu Persetujuan Guru
              </span>
            </div>

            <div className="space-y-4">
              {draftQuestions.map((q, qIdx) => (
                <div
                  key={q.id || qIdx}
                  className="clay-card clay-card-hover clay-white p-6 space-y-3.5"
                >
                  <div className="flex justify-between items-start">
                    <div className="flex items-center gap-2">
                      <span className="w-7 h-7 rounded-xl bg-[#1C1E26] text-white flex items-center justify-center text-xs font-black">
                        {qIdx + 1}
                      </span>
                      <span className="clay-pill clay-lavender text-[10px] font-extrabold px-2.5 py-0.5 text-[#4B3B7A]">
                        Level {q.difficulty}
                      </span>
                    </div>
                    <span className="clay-pill bg-[#F8F9FD] text-[10px] font-mono font-bold text-[#5A5E70] px-2.5 py-1">
                      {q.sourceReference}
                    </span>
                  </div>

                  <p className="text-sm font-black text-[#010105] leading-relaxed">
                    {q.questionText}
                  </p>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 pt-1">
                    {q.options.map((opt: string, optIdx: number) => (
                      <div
                        key={optIdx}
                        className={`p-3 rounded-2xl text-xs font-bold border transition-all ${
                          optIdx === q.correctIndex
                            ? "clay-card clay-mint text-[#1D5E4D] border-[#1D5E4D]"
                            : "bg-[#F8F9FD] border-[rgba(28,30,38,0.06)] text-[#5A5E70]"
                        }`}
                      >
                        <span className="font-black mr-1.5">{String.fromCharCode(65 + optIdx)}.</span>
                        {opt}
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>

            {/* Bottom Actions */}
            <div className="pt-4 flex flex-col sm:flex-row items-center justify-between gap-4">
              {isPublished ? (
                <div className="clay-pill clay-mint px-4 py-2 flex items-center gap-2 text-xs font-black text-[#1D5E4D]">
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Kuis berhasil disetujui &amp; diterbitkan ke portal siswa!</span>
                </div>
              ) : (
                <span className="text-xs text-[#5A5E70] font-medium">
                  Pastikan seluruh soal telah ditelaah sesuai kurikulum sebelum diterbitkan.
                </span>
              )}

              <button
                onClick={handlePublishToClass}
                disabled={draftQuestions.length === 0}
                className="clay-btn clay-btn-dark px-6 py-3 text-xs font-black shadow-md w-full sm:w-auto flex items-center justify-center gap-2 cursor-pointer"
              >
                <CheckCircle2 className="w-4 h-4" />
                <span>Setujui &amp; Terbitkan Kuis ke Portal Siswa</span>
              </button>
            </div>
          </section>
        </main>
      </div>
    </div>
  );
}
